### ISSUE TITLE
Warnings and errors when running RasPi2-3-4-deploy.sh 

### ISSUE THREAD

**Issue by ddd999** [stephendade/Rpanion-server#160]
I got this warning when running the RasPi2-3-4-deploy.sh script on a fresh install of Raspbian 11 on a Pi Zero 2 W:

>                           SCRIPT DEPRECATION WARNING
> 
>  This script, located at https://deb.nodesource.com/setup_X, used to
>   install Node.js is deprecated now and will eventually be made inactive.
> 
>   Please visit the NodeSource distributions Github and follow the
>   instructions to migrate your repo.
>   https://github.com/nodesource/distributions
> 
>   The NodeSource Node.js Linux distributions GitHub repository contains
>   information about which versions of Node.js and which Linux distributions
>   are supported and how to install it.
>   https://github.com/nodesource/distributions
> 
> 
>                           SCRIPT DEPRECATION WARNING

Then later on I get:

> + npm install
> (node:13560) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:13560) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:13560) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated express-pino-logger@7.0.0: use pino-http instead
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

and then, finally it exits with an error:

> + npm run build
> 
> > Rpanion-server@0.9.0 build
> > DISABLE_ESLINT_PLUGIN=true react-scripts build
> 
> node:internal/modules/cjs/loader:423
>       throw err;
>       ^
> 
> Error: Cannot find module '/home/pi/Rpanion-server/node_modules/dotenv-expand/lib/main.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (node:internal/modules/cjs/loader:415:19)
>     at Module._findPath (node:internal/modules/cjs/loader:665:18)
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
>     at Module._load (node:internal/modules/cjs/loader:901:27)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at /home/pi/Rpanion-server/node_modules/react-scripts/config/env.js:43:5
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/home/pi/Rpanion-server/node_modules/react-scripts/config/env.js:41:13)
>     at Module._compile (node:internal/modules/cjs/loader:1233:14) {
>   code: 'MODULE_NOT_FOUND',
>   path: '/home/pi/Rpanion-server/node_modules/dotenv-expand/package.json',
>   requestPath: 'dotenv-expand'
> }
> 
> Node.js v20.5.1
>

**Comment by stephendade** [comment]
I've just tested this on a Pi ZeroW2 using RasPiOS Bullseye (11). I did get some warnings with ``npm install``, but no errors on the ``npm run build`` step.

This was using nodejs 20.6.1

Could you try again? I've just merged in a better nodejs install method.

**Comment by ddd999** [comment]
I tried again with a (new) fresh install of Raspbian Lite, and it worked without errors. Thanks!

I did still get the "Possible EventEmitter memory leak detected." warning a bunch of times but it seemed to still complete the installation fine despite that.
